# Generated by Django 3.2.16 on 2023-01-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230118_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='users',
            new_name='user',
        ),
    ]
